# Generated by Django 3.1.2 on 2021-01-05 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("memberaudit", "0003_stats_n_skillset_autocomplete"),
        ("eveuniverse", "0004_effect_longer_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberAuditComplianceFilter",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=500)),
            ],
            options={
                "verbose_name": "compliance filter",
                "verbose_name_plural": "compliance filters",
            },
        ),
        migrations.CreateModel(
            name="MemberAuditSkillSetFilter",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=500)),
                (
                    "skill_sets",
                    models.ManyToManyField(
                        help_text="Users must possess all of the skills in <strong>one</strong> of the selected skillsets.",
                        to="memberaudit.SkillSet",
                    ),
                ),
            ],
            options={
                "verbose_name": "skill set filter",
                "verbose_name_plural": "skil set filters",
            },
        ),
        migrations.CreateModel(
            name="MemberAuditAssetFilter",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=500)),
                (
                    "assets",
                    models.ManyToManyField(
                        help_text="User must possess <strong>one</strong> of the selected assets",
                        to="eveuniverse.EveType",
                    ),
                ),
            ],
            options={
                "verbose_name": "asset filter",
                "verbose_name_plural": "asset filters",
            },
        ),
    ]
