# Generated by Django 3.1.2 on 2021-01-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memberaudit_securegroups", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberAuditActivityFilter",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="The filter description that is shown to end users",
                        max_length=500,
                    ),
                ),
                (
                    "inactivity_threshold",
                    models.PositiveIntegerField(
                        help_text="Maximum allowable inactivity, in <strong>days</strong>."
                    ),
                ),
            ],
            options={
                "verbose_name": "activity filter",
                "verbose_name_plural": "activity filters",
            },
        ),
        migrations.CreateModel(
            name="MemberAuditAgeFilter",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="The filter description that is shown to end users",
                        max_length=500,
                    ),
                ),
                (
                    "age_threshold",
                    models.PositiveIntegerField(
                        help_text="Minimum allowable age, in <strong>days</strong>."
                    ),
                ),
            ],
            options={
                "verbose_name": "age filter",
                "verbose_name_plural": "age filters",
            },
        ),
        migrations.CreateModel(
            name="MemberAuditSkillPointFilter",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="The filter description that is shown to end users",
                        max_length=500,
                    ),
                ),
                (
                    "skill_point_threshold",
                    models.PositiveBigIntegerField(
                        help_text="Minimum allowable skillpoints"
                    ),
                ),
            ],
            options={
                "verbose_name": "skill point filter",
                "verbose_name_plural": "skill point filters",
            },
        ),
        migrations.AlterField(
            model_name="memberauditassetfilter",
            name="description",
            field=models.CharField(
                help_text="The filter description that is shown to end users",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="memberauditcompliancefilter",
            name="description",
            field=models.CharField(
                help_text="The filter description that is shown to end users",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="memberauditskillsetfilter",
            name="description",
            field=models.CharField(
                help_text="The filter description that is shown to end users",
                max_length=500,
            ),
        ),
    ]
