# Generated by Django 4.2.16 on 2024-12-06 00:39

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memberaudit_securegroups", "0005_alter_corporationrolefilter_role"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activityfilter",
            options={
                "verbose_name": "Smart Filter: Activity",
                "verbose_name_plural": "Smart Filter: Activity",
            },
        ),
        migrations.AlterModelOptions(
            name="agefilter",
            options={
                "verbose_name": "Smart Filter: Character Age",
                "verbose_name_plural": "Smart Filter: Character Age",
            },
        ),
        migrations.AlterModelOptions(
            name="assetfilter",
            options={
                "verbose_name": "Smart Filter: Asset",
                "verbose_name_plural": "Smart Filter: Asset",
            },
        ),
        migrations.AlterModelOptions(
            name="compliancefilter",
            options={
                "verbose_name": "Smart Filter: Compliance",
                "verbose_name_plural": "Smart Filter: Compliance",
            },
        ),
        migrations.AlterModelOptions(
            name="corporationrolefilter",
            options={
                "verbose_name": "Smart Filter: Corporation Role",
                "verbose_name_plural": "Smart Filter: Corporation Role",
            },
        ),
        migrations.AlterModelOptions(
            name="corporationtitlefilter",
            options={
                "verbose_name": "Smart Filter: Corporation Title",
                "verbose_name_plural": "Smart Filter: Corporation Title",
            },
        ),
        migrations.AlterModelOptions(
            name="skillpointfilter",
            options={
                "verbose_name": "Smart Filter: Skill Points",
                "verbose_name_plural": "Smart Filter: Skill Points",
            },
        ),
        migrations.AlterModelOptions(
            name="skillsetfilter",
            options={
                "verbose_name": "Smart Filter: Skill Set",
                "verbose_name_plural": "Smart Filter: Skill Set",
            },
        ),
        migrations.AlterModelOptions(
            name="timeincorporationfilter",
            options={
                "verbose_name": "Smart Filter: Time in Corporation",
                "verbose_name_plural": "Smart Filter: Time in Corporation",
            },
        ),
        migrations.AddField(
            model_name="compliancefilter",
            name="reversed_logic",
            field=models.BooleanField(
                default=False,
                help_text="If set all members WITHOUT compliance will pass this check.",
            ),
        ),
    ]
