# Generated by Django 4.2.17 on 2024-12-31 13:00

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memberaudit_securegroups", "0006_compliance_reverse_logic_and_filter_names"),
    ]

    operations = [
        migrations.AddField(
            model_name="timeincorporationfilter",
            name="reversed_logic",
            field=models.BooleanField(
                default=False,
                help_text="If set, all members with LESS than the minimum days will pass this check.",
            ),
        ),
    ]
