# Generated by Django 4.2.16 on 2024-10-24 13:31

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memberaudit_securegroups", "0006_alter_meta_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="compliancefilter",
            name="reversed_logic",
            field=models.BooleanField(
                default=False,
                help_text="If set all members WITHOUT compliance will pass this check.",
            ),
        ),
    ]
