# Generated by Django 4.2.23 on 2025-07-25 20:34

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memberaudit", "0020_add_new_roles"),
        ("memberaudit_securegroups", "0007_timeincorporationfilter_reversed_logic"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeStationFilter",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="The filter description that is shown to end users.",
                        max_length=500,
                    ),
                ),
                (
                    "include_alts",
                    models.BooleanField(
                        default=False,
                        help_text="When True, the filter will also include the users alt-characters.",
                    ),
                ),
                (
                    "home_station",
                    models.ForeignKey(
                        help_text="User must have a character with this home station.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="home_station_filter",
                        to="memberaudit.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "Smart Filter: Home Station (Death Clone)",
                "verbose_name_plural": "Smart Filter: Home Station (Death Clone)",
            },
        ),
    ]
