# Generated by Django 4.2.25 on 2025-10-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memberaudit_securegroups", "0008_homestationfilter"),
    ]

    operations = [
        migrations.CreateModel(
            name="VisibilityFilter",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="The filter description that is shown to end users.",
                        max_length=500,
                    ),
                ),
                (
                    "reversed_logic",
                    models.BooleanField(
                        default=False,
                        help_text="If set all members WITHOUT visibility will pass this check.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Smart Filter: Visibility",
                "verbose_name_plural": "Smart Filter: Visibility",
            },
        ),
    ]
