# Generated by Django 4.2.25 on 2025-10-22 22:32

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memberaudit_securegroups", "0008_homestationfilter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compliancefilter",
            name="reversed_logic",
            field=models.BooleanField(
                default=False,
                help_text="If set, all members WITHOUT compliance will pass this check.",
            ),
        ),
    ]
